# Boek‐instellingen
title: CO₂-uitstoot van de landbouwsector
author: Carmen van der Lans, Jette Walvis, Sarah Schaefers, Nur Shidai
logo: logo.png

execute:
  execute_notebooks: force

repository:
  url: https://github.com/CarmenvanderLans/Information-Vis
  path_to_book: .
  branch: main

# HTML-themaopties + Plotly.js clientside library
html:
  use_repository_button: true
  use_issues_button: true
  favicon: logo.png
  collapse_input: true      # álle cellen standaard dichtklappen
  # (optioneel kun je hier toggle‐knoplabels aanpassen met code_prompt_show / hide)

# Myst-NB globale hide/remove instellingen
mystnb:
  remove_code_source: true  # verwijder alle code‐inputs volledig

toc:
  includehidden: false
  show: false

js_files:
  - https://cdn.plot.ly/plotly-latest.min.js

extra_path:
  - iframe_figures
