# Book settings
title: CO₂-uitstoot van de landbouwsector
author: Carmen van der Lans, Jette Walvis, Sarah Schaefers, Nur Shidai
logo: logo.png

# Force re-execution of notebooks on each build
execute:
  execute_notebooks: force

# Settings for LaTeX/PDF builds (on dezelfde manier als je al had)
latex:
  latex_documents:
    - intro          # key voor deze PDF-output
    - book.tex       # → book.tex → book.pdf
    - "CO₂-uitstoot van de landbouwsector"
    - manual

# Repository information for “Edit on GitHub” links
repository:
  url: https://github.com/CarmenvanderLans/Information-Vis
  path_to_book: .
  branch: main

# Sphinx-extensions om Plotly-figuren client-side in te laden
sphinx:
  extra_extensions:
    - sphinxext.plotly_directive
  config:
    # Dit laadt Plotly.js in in elk HTML-pagina
    html_js_files:
      - https://cdn.plot.ly/plotly-latest.min.js

# HTML theme options
html:
  use_repository_button: true
  use_issues_button:    true
  favicon:              logo.png
