# Book settings
title: CO2-uitstoot van de landbouwsector
author: Carmen van der Lans, Jette Walvis, Sarah Schaefers, Nur Shidai
logo: logo.png

# Force re-execution of notebooks on each build
execute:
  execute_notebooks: force

# Information for PDF (LaTeX) builds
latex:
  latex_documents:
    - targetname: book.tex
      title: "CO2-uitstoot van de landbouwsector"
      author: "Carmen van der Lans, Jette Walvis, Sarah Schaefers, Nur Shidai"
      documentclass: manual

# Repository information for “Edit on GitHub” links
repository:
  url: https://github.com/CarmenvanderLans/Information-Vis
  path_to_book: .
  branch: main

# HTML theme options
html:
  use_repository_button: true
  use_issues_button: true
  favicon: logo.png
