
title: CO₂-uitstoot van de landbouwsector
author: Carmen van der Lans, Jette Walvis, Sarah Schaefers, Nur Shidai
logo: logo.png


execute:
  execute_notebooks: force


latex:
  latex_documents:
    - intro          # key voor PDF-output
    - book.tex       # → book.tex → book.pdf
    - "CO₂-uitstoot van de landbouwsector"
    - manual


repository:
  url: https://github.com/CarmenvanderLans/Information-Vis
  path_to_book: .
  branch: main

sphinx:
  extra_extensions:
    - sphinxext.plotly_directive

html:
  use_repository_button: true
  use_issues_button:    true
  favicon:              logo.png

  # hier móet onder _html_ komen, NIET onder sphinx.config
  js_files:
    - https://cdn.plot.ly/plotly-latest.min.js
